name: My First 

on: 
 push: 
 branch: main 

 workflow_dispatch:

jobs:
  first_job:
    runs-on: ubuntu-latest

    steps:
      - name: welcome message 
        run: echo " my first github job"

      - name: list files
        run: ls

      - name: Read files
        run: cat README.md  
